[manager]
show_hidden = true

[opener]
edit = [{ run = '/usr/bin/nvim "$@"', block = true, for = "unix" }]

view = [{ run = '/usr/bin/zathura "$@"', orphan = true, for = "unix" }]

play = [{ run = '/usr/bin/mpv "$@"', orphan = true, for = "unix" }]

open = [{ run = '/usr/bin/libreoffice "$@"' }]

[open]
rules = [
  { mime = "text/*", use = "edit" },

  { name = "*.pdf", use = "view" },

  { name = "*.mkv", use = "play" },
  { name = "*.mp4", use = "play" },
  { name = "*.avi", use = "play" },
  { name = "*.mov", use = "play" },
  { name = "*.webm", use = "play" },

  { name = "*.jpg", use = "view" },
  { name = "*.jpeg", use = "view" },
  { name = "*.png", use = "view" },
  { name = "*.gif", use = "view" },

  { name = "*.doc", use = "open" },
  { name = "*.docx", use = "open" },
  { name = "*.odt", use = "open" },
  { name = "*.pptx", use = "open" },
]

[preview]
max_width = 1980
max_height = 1080
